workspace:
    base: /go
    path: src/github.com/SierraSoftworks/stablehand

pipeline:

    go:build:
        image: golang:1.6
        commands:
            - go get ./...
            - go test ./...
            - "CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-s' -o stablehand '-X main.tag=${DRONE_TAG=v1.0.0}' '-X main.sha=${DRONE_COMMIT:0:6}' '-X main.branch=${DRONE_BRANCH=dev}'"

    docker:
        repo: sierrasoftworks/stablehand
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
            - "go"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"